### ISSUE TITLE
Nova File Field Gives IsValid Error

### ISSUE THREAD

**Issue by Milkhan** [optimistdigital/nova-translatable#13]
Thank you for this helpful package!
But when I use this with Nova File field, it  gives `Call to a member function isValid() on array` error. Am I doing something wrong?

**Comment by Tarpsvo** [comment]
Hi! That's weird, I wasn't able to reproduce this issue on version 1.4.1. Did you do any customizations on the file?

**Comment by Milkhan** [comment]
No, I was trying to upload just audio files.

**Comment by Equruler** [comment]
+1 for Image Field
Laravel v7.6.2
Nova v3.4.0
Nova-translatable 1.5.2

@Tarpsvo 
In your success case, what is the type of the variable $file in 
vendor/laravel/nova/src/Fields/File.php:309

is it an array?

**Comment by Tarpsvo** [comment]
Ah crap. File field overwrites `fillAttribute` from  `Field` which it extends and doesn't call the `fillCallback`. I think the only way around this might be to create a TranslatableFile field. 🤔

**Comment by Equruler** [comment]
@Tarpsvo 
I am not urgent for this, I use your media-field instead now. Works great.

**Comment by DurandSacha** [comment]
I have a same problem ! Nova-translatable, how to make laravel nova accept fileType file translations ?
