### ISSUE TITLE
Boolean fields can't interpret boolean translated value

### ISSUE THREAD

**Issue by David-YesWeDev** [optimistdigital/nova-translatable#14]
Hi ! Thank you for your package ! This is great :)

Unfortunately i have a problem :( wich is that the boolean fields doesn't read correct boolean values in the database. For exemple i set this fields : 

```
Boolean::make('Présence sur page d\'accueil', 'is_on_home')
->translatable()
->hideFromIndex(),

Boolean::make('Bannière accueil', 'is_on_banner')
->translatable()
->hideFromIndex(),

Boolean::make('Est mis en avant sur la page d\'accueil', 'is_highlighted')
->translatable()
->hideFromIndex(),
```

The data is correctly stored in the database (here i unchecked all cheboxes) : 

is_on_home : `{"fr":"0","es":"0","ma":"0"}`
is_on_banner : `{"fr":"0","es":"0","ma":"0"}`
is_highlighted : `{"fr":"0","es":"0","ma":"0"}`

But when i navigate to the nova admin, my field's values are always displayed as true :

![boolean-ob-bug](https://user-images.githubusercontent.com/32599362/78796349-77415300-79b6-11ea-9e36-c10339c6901f.png)

Do you have any idea where this might have come from?

Thank you for your help and time !

**Comment by PaulLawton227** [comment]
What was the fix for this please? We're still on v3 of Nova - so can't use the latest version (as it requires v4)

**Comment by aliwesome** [comment]
Hey @Tarpsvo, I'm on `v1.12.0` and I have this issue.

**Comment by marcelosantos89** [comment]
This problem still happen with Nova 4 and "nova-page-manager": "^5.8" (that adds nova-translatable)
