### ISSUE TITLE
is_nan errro

### ISSUE THREAD

**Issue by mstaack** [optimistdigital/nova-translatable#17]
updated to latest version,

now seeing these quite often:
```is_nan() expects parameter 1 to be float, string given```

**Comment by mstaack** [comment]
thx @Tarpsvo 
https://github.com/optimistdigital/nova-translatable/commit/a0722b4052585b3a85d8e86a3d14919fb3205163 ;)

**Comment by Tarpsvo** [comment]
Hey! Sorry about that, fixed it in version 1.5.1 by replacing the `is_nan` check with `is_numeric`. Good luck!

**Comment by Tarpsvo** [comment]
Actually, 1.5.2. I made a typo with the is_numeric checks.

**Comment by mstaack** [comment]
no problem, thanks for quick response
