### ISSUE TITLE
Not Appropriate method when rendering value, which will cause nova media field error

### ISSUE THREAD

**Issue by Equruler** [optimistdigital/nova-translatable#19]
https://github.com/optimistdigital/nova-translatable/blob/848406bc4db9079677563804edfc3c012a4819f6/src/TranslatableFieldMixin.php#L45

I found this line is not appropriate.

In database, if we saved something like '{"en": "4", "hk": "5"}', then the expected value should be (string) "4" instead of (float) 4.

Only '{"en": 4, "hk": 5} should render (float) 4

I found this because there is an error when combine nova-translatable and nova-media-field.

https://github.com/optimistdigital/nova-media-field/blob/ea08f90f61e8824c0c60813c7390e3aaab449b99/resources/js/components/FormField.vue#L155
The vue.js can not run .split on number, the expected this.field.value should be a string.

Hope this will be fixed.

Thanks!

**Comment by Equruler** [comment]
https://github.com/optimistdigital/nova-translatable/blob/848406bc4db9079677563804edfc3c012a4819f6/src/TranslatableFieldMixin.php#L75

Sorry, I found that this line will also make the string to number...
But this line will go very deep, I am not sure which party cause it or if it is appropriate actually.

**Comment by Tarpsvo** [comment]
Hi! I released `nova-media-field` properly now with version 1.0.0. It also fixes the issue you encountered. Just run `composer require optimistdigital/nova-media-field` and remove the previous dependency on the `stable` branch and you're ready to go. Good luck!

**Comment by Equruler** [comment]
It works! Thanks!
