### ISSUE TITLE
Translatable on KeyValue field does not work

### ISSUE THREAD

**Issue by ngiraud** [optimistdigital/nova-translatable#2]
Hi, first of all thanks for this package, it is great !

I'm trying to make it work with a KeyValue field on a Form page.

First, when you click to switch the locale, it seems working. But when you click back to the previous locale, the value is splitted. If I continue switching my locales, the content is splitted again from the previous splitted content. I made some screenshots for a better understanding.

![three](https://user-images.githubusercontent.com/12152071/72748585-eda09700-3bb7-11ea-83ed-d5d614ebef84.png)
![two](https://user-images.githubusercontent.com/12152071/72748586-eda09700-3bb7-11ea-965e-4370853f9eac.png)
![one](https://user-images.githubusercontent.com/12152071/72748587-eda09700-3bb7-11ea-9941-cd656ac6b259.png)

On the Detail page, I only see [object Object] in both tabs.

Thanks

**Comment by Tarpsvo** [comment]
Hey there! Sorry for the late reply, I was on vacation for the week.

Thanks a ton for the pull requests! I merged both of them and released the fixes you provided in version 1.2.0. Hope it works for you now. :)
