### ISSUE TITLE
htmlspecialchars() expects parameter 1 to be string, array given

### ISSUE THREAD

**Issue by milewski** [optimistdigital/nova-translatable#20]
![image](https://user-images.githubusercontent.com/2874967/80480206-d0335400-8982-11ea-8a65-00202c7d3227.png)

![image](https://user-images.githubusercontent.com/2874967/80480308-fe189880-8982-11ea-8a43-1692a509ce7f.png)

Hi I got this error on details page when using a Textarea field

**Comment by Tarpsvo** [comment]
Thanks a ton for reporting and fixing this, released both of your fixes in version 1.5.4! Good luck!
