### ISSUE TITLE
Empty fields result in strange value stored in database

### ISSUE THREAD

**Issue by voidgraphics** [optimistdigital/nova-translatable#22]
Hi! 

I have a very simple setup, a translatable text field like so:

```php
Text::make('Slug', 'slug')->translatable(),
```

and two languages configured in my application: `fr (default)` and `de`.

If I leave the slug field empty for both languages and save, it results in the following being saved to the database: `{"de":null}`.

The `fr` key is missing.

**Comment by voidgraphics** [comment]
After some digging, this seems to be a bug with `spatie/nova-translatable` and not this package, my apologies.

**Comment by Tarpsvo** [comment]
Hmm, so these two conflicted somehow?

**Comment by voidgraphics** [comment]
This is not a problem with your package, but if you're curious, here's what happened:

In Spatie's `HasTranslations.php`, at line 68, there is the following code

```php
return array_filter(json_decode($this->getAttributes()[$key] ?? '' ?: '{}', true) ?: [], function ($value) {
    return $value !== null && $value !== '';
});
```

It seems that they are intentionally filtering out the empty values.

If I remove the array_filter:

```php
return json_decode($this->getAttributes()[$key] ?? '' ?: '{}', true) ?: [];
```

Then I get the expected `{"fr":null,"de":null}` value in the database.
