### ISSUE TITLE
Validation errors not being displayed under the invalid input

### ISSUE THREAD

**Issue by andrefedalto** [optimistdigital/nova-translatable#29]
Hi. I'm facing an issue with the validation errors not being displayed underneath the invalid field (see attached image). I started from a clean install and a regular field is being validated and the error is being displayed, but the `->translatable()` field, although being validated and the error message returned in the request, is not working. It even recognizes there's an issue with the field in one of the translations but the error apparently doesn't get binded to the field.

I'm runnig `optimistdigital/nova-translatable@1.5.6`, `laravel/nova@3.6.0` and `laravel/framework@7.6.2`. 

![image](https://user-images.githubusercontent.com/1895494/83923271-47b18b80-a758-11ea-9464-1779ce27c5d8.png)

**Comment by webstack9** [comment]
Hi for some who needs quick solution:
file: resources/js/mixins/TranslatableField.js

Append locale to validationKey prop:  **validationKey: `${this.field.attribute}.${locale.key}`**
like this:

`this.fields = {};
    this.locales.forEach(
      locale =>
        (this.fields[locale.key] = {
          ...this.field,
          value: initialValues[locale.key] || '',
          attribute: `${this.field.attribute}.${locale.key}`, // Append '.en' to avoid duplicate ID-s in DOM
          validationKey: `${this.field.attribute}.${locale.key}` // Append locale to validationKey
        })
    );`

@andrefedalto Tested on my machine and its working.

@Tarpsvo is this fix satisfying to be included in next release?

**Comment by Tarpsvo** [comment]
As mentioned in the PR, fix released in 1.5.7. Thanks a ton!
