### ISSUE TITLE
Workaround for nova advanced media library

### ISSUE THREAD

**Issue by matteopoile** [optimistdigital/nova-translatable#32]
Hi,
first of all... Great Package!
I red that the library support nova advanced media library with a workaround.

I need to make translatable some custom fields added to [ebess/advanced-nova-media-library](https://github.com/ebess/advanced-nova-media-library) so I can upload a single image and translate only related custom fields but I can't figure out how.

It seems like ->translatable() method is ignored when using advanced media library custom property as you can see on the attached image:

![Schermata 2020-07-01 alle 19 19 56](https://user-images.githubusercontent.com/492385/86273105-059d2d80-bbd0-11ea-9fcb-209770591552.png)

Any suggestions will be truly appreciated

**Comment by Tarpsvo** [comment]
Hi! I was incorrect in assuming the advanced nova media library package worked. It apparently has removed the `resolveCallback` calling functionality and the translatable field is not able to initialize itself. :(
