### ISSUE TITLE
Default Values

### ISSUE THREAD

**Issue by RakivskyiMax** [optimistdigital/nova-translatable#35]
Hi there!

```
optimistdigital/nova-translatable        1.6.3
laravel/nova                             v3.11.1
```

While creating my resource I'm trying to make a default value for field using "Default Values" from Laravel Nova.
As a result I receive an empty field. 

[https://nova.laravel.com/docs/3.0/resources/fields.html#default-values](https://nova.laravel.com/docs/3.0/resources/fields.html#default-values)

Example:

```PHP
           Text::make(__('Description'), 'description')
                ->default([
                    'en' => 'test en',
                    'pl' => 'test pl'
                ])
                ->translatable()
```

![2020-10-06 14 39 42](https://user-images.githubusercontent.com/17813262/95197518-6301d580-07e2-11eb-94bb-56b22b69c6f1.png)

Seems like your library does not support this feature, or there is another way to do it correctly?

Please let me know if you are going to fix it in nearest future.
 
Thank you.

**Comment by KasparRosin** [comment]
Sorry for the late response, this feature is now available with version 1.6.10.
