### ISSUE TITLE
Issue with text area

### ISSUE THREAD

**Issue by milewski** [optimistdigital/nova-translatable#37]
Hi there is an issue with text area, it works fine on edit, however when opening the detail views it throws this error:

![image](https://user-images.githubusercontent.com/2874967/97843472-5363a700-1d24-11eb-8656-b90249f01090.png)

It works fine if i use a Text:: instead of Textarea::

**Comment by Tarpsvo** [comment]
That's weird, I tested it and can't seem to reproduce it on my machine. What Nova version are you using?

**Comment by Tarpsvo** [comment]
Think I got it - it happened when the Textarea was inside a Flexible field. Try out 1.6.9.

**Comment by milewski** [comment]
Uhm wasn't really using it inside a flexible field.. look this was my setup:

![image](https://user-images.githubusercontent.com/2874967/97937546-f9152580-1db9-11eb-9561-959e95d563a9.png)

**Comment by milewski** [comment]
But `1.6.9` did seem to have fixed the issue, now it is no longer throwing that error. thanks!
