### ISSUE TITLE
Sortable option and search not work correctly

### ISSUE THREAD

**Issue by yammycode** [optimistdigital/nova-translatable#39]
Hello!
First, thanks for the lovely package.
But.
Sorting doesn't work.
https://prnt.sc/vqefg9
https://prnt.sc/vqefri

And case insensitive search doesn't work.
https://prnt.sc/vqeg5r
https://prnt.sc/vqege5

Laravel 8, Nova 3.15.0, MySql 5.7

Please help solve these problems!

**Comment by Tarpsvo** [comment]
Hi!

This package might affect sorting depending on the database driver.  Here's an example of how to get around this:

```
Text::make('City', 'name->en')->displayUsing(fn () => $this->name)->sortable()->onlyOnIndex(),
```

Case sensitive search is Nova's issue, sadly.

**Comment by yammycode** [comment]
Thank you so much for your help with sorting!

By search - yes, I understand that this is a feature of Nova. Rather, it’s a search feature for mysql and json-field. I even wrote a issue in Nova support. But they decided that this is not a bug and the request was closed. I was hoping this is a common problem and that there might be a known solution.
Anyway - thanks for your help!

**Comment by Tarpsvo** [comment]
I usually extend the Resource class in my projects and overwrite the following method in it, which allows for case-insensitive search:

```
protected static function applySearch($query, $search)
    {
        return $query->where(function ($query) use ($search) {
            $model = $query->getModel();
            $connectionType = $query->getModel()->getConnection()->getDriverName();
            $canSearchPrimaryKey = is_numeric($search) &&
                in_array($query->getModel()->getKeyType(), ['int', 'integer']) && ($connectionType != 'pgsql' || $search <= PHP_INT_MAX) &&
                in_array($query->getModel()->getKeyName(), static::$search);

            if ($canSearchPrimaryKey) {
                $query->orWhere($query->getModel()->getQualifiedKeyName(), $search);
            }

            $likeOperator = $connectionType == 'pgsql' ? 'ilike' : 'like';

            $query->orWhere(function ($query) use ($search, $model, $likeOperator) {
                foreach (static::searchableColumns() as $column) {
                    $qColumn = $model->qualifyColumn($column);
                    $qSearch = mb_strtoupper($search);
                    $query->orWhereRaw("UPPER($qColumn) $likeOperator ?", ["%$qSearch%"]);
                }
            });
        });
    }
```

**Comment by yammycode** [comment]
WOW! Thank you very much!
