### ISSUE TITLE
translation tab ordering

### ISSUE THREAD

**Issue by gianmarx** [optimistdigital/nova-translatable#42]
i created this field to translate

```
Text::make('Title')
                ->rules('required', 'min:2')
                ->translatable([
                    'fr' => 'French',
                   'es' => 'Spanish',
                    'ru' => 'Russian'
                ]),

```
 but i noticed that the tabs are sorted in alphabetical order, is there a possibility to give them a different order?

I would like to see them in the order I put them in the field translatable instead I see them in alphabetical order

![Schermata 2020-12-22 alle 11 42 57](https://user-images.githubusercontent.com/57480315/102879926-d82c9080-444a-11eb-858d-6dd690aa7116.png)

**Comment by Tarpsvo** [comment]
Hi! They're not in alphabetical order. Instead, the first language will always be the language the Nova panel is in (`app()->locale() / config('app.locale', 'en')`). The rest are in the order they're defined in.

I think it makes sense, does it not?

**Comment by Tarpsvo** [comment]
Heya! The most recent update, 1.9.0, allows configuring the order of the locales. If you want the array order to be respected, you can set `prioritize_nova_locale` to `false` in `config/nova-translatable.php`. :) Good luck!
