### ISSUE TITLE
Illuminate\Database\Grammar::parameterize() must be of the type array

### ISSUE THREAD

**Issue by Tagra** [optimistdigital/nova-translatable#45]
Getting error when trying to saving resource 

> Argument 1 passed to Illuminate\Database\Grammar::parameterize() must be of the type array, string given, called in /var/www/autocat/vendor/laravel/framework/src/Illuminate/Database/Query/Grammars/Grammar.php on line 884

Just added:
`            Text::make('Title')
            ->rules('required')
            ->translatable(),`

Versions:
`   
        "laravel/framework": "^7.0",
        "laravel/nova": "~3.0",
 "optimistdigital/nova-translatable": "^1.6",
        "spatie/laravel-translatable": "^4.6",
`

**Comment by cliche23** [comment]
I have the same issue. What was the fix for this?

**Comment by Tarpsvo** [comment]
You might have to add $casts = ['title' => 'array'] to your model.

**Comment by ConstantMath** [comment]
Hi, first thanks a;ot for your work on this package.
I also have the same issue, adding the `$casts = ['title' => 'array']`at the begining of the class model does not resolve it.
Can you please explain what is causing that ?
I have the latest versions of the above mentioned packages.
Best,
