### ISSUE TITLE
Method Laravel\Nova\Fields\Text::resolveDefaultValue does not exist

### ISSUE THREAD

**Issue by nikolayynayydenov** [optimistdigital/nova-translatable#52]
Hi, I am using Laravel 6.20.6, Nova 2.9.2 and spatie/laravel-translatable 4.6.0. This is my setup in the model:

```
use HasTranslations;
public $translatable = ['name'];
```
When I try to use this package like so:

```
Text::make('name')
      ->rules('required', 'max:255')
      ->translatable(),
```

I get this error: Method Laravel\Nova\Fields\Text::resolveDefaultValue does not exist.

**Comment by Tarpsvo** [comment]
Ah crap, it seems like that ->default() added in version 3.4.0. I released version 1.8.3 which should fix support for Nova 2.9. Good luck!
