### ISSUE TITLE
Example of usage trasnlatable with ebess/advanced-nova-media-library

### ISSUE THREAD

**Issue by thalegion** [optimistdigital/nova-translatable#60]
Hello @Tarpsvo. 

According to docs it should be possible to made media fields from `ebess/advanced-nova-media-library` translatable, but looks like it doesn't works out of the box. Seems that `ebess/advanced-nova-media-library` just ignore callback that this package set.

So docs are incorrect or maybe you can provide example of usage with `ebess/advanced-nova-media-library`?

Thank you!

**Comment by Tarpsvo** [comment]
Ah okay - it does seem the docs are incorrect. I looked at the Advanced Nova Media Library documentation and it seems that they don't call the `resolveCallback` necessary to initialize the translatable functionality. Sorry for the confusion!
