### ISSUE TITLE
zero-leading error

### ISSUE THREAD

**Issue by yammycode** [optimistdigital/nova-translatable#62]
Hello!
I found the problem. I need to provide some bank details. For example, BIC 0123456. In this case, 0 is an integral part of the value. However, when saving, the leading 0 disappears and I get the value 123456. How do I solve this problem?

**Comment by Tarpsvo** [comment]
Hi! What field type are you using?

**Comment by yammycode** [comment]
Type  text.
Text::make('Текст', 'text')->translatable()

**Comment by Tarpsvo** [comment]
Hi! There was indeed an issue with this - the numeric value was being converted to a number and it lost its starting zero. I fixed it in version 1.11.0. Sorry about the delay as well and thanks for reporting this! Good luck!

**Comment by yammycode** [comment]
Thank you!
