### ISSUE TITLE
Work with Image Field of whitecube/nova-flexible-content

### ISSUE THREAD

**Issue by Equruler** [optimistdigital/nova-translatable#7]
Hello,

You are the best Nova Translatable Package for spatie/translatable!

I am now trying to work with whitecube/nova-flexible-content.
If I need something translate in Flexible, do you have any idea to do it?
```php
    public function fields(Request $request)
    {
        return [
            ID::make()->sortable(),
            Text::make('Title')->sortable()->translatable(),
            Textarea::make('Description')->alwaysShow()->translatable(),
            Image::make('Thumbnail'),
            Flexible::make('Images')
                ->addLayout('Image Item', 'item', [
                    Image::make('Image')->translatable(),
                ]),
            Trix::make('Content')->alwaysShow()->translatable(),
        ];
    }
```

I am trying to translate Image in Flexible, but finally it return error:
Call to a member function isValid() on array

And it can not upload both languages images at the same time.

Appreciated if you have idea on it!

Your package helps much!

**Comment by Tarpsvo** [comment]
I managed to get fields other than Image working inside Nova Flexible Content. I'm not sure how to get the Image field to work though. I'll give it another try soon.

**Comment by voidgraphics** [comment]
@Tarpsvo did you get those fields to work like @Equruler mentioned?

It's my understanding that the translated fields need to be referred to in the `public $translatable` property, which you can not do by having inline layouts like shown in the question. You would need to have [a Layout class](https://whitecube.github.io/nova-flexible-content/#/?id=custom-layout-classes) to do this. Right?

**Comment by Tarpsvo** [comment]
Image and File fields are currently not supported, sadly.
